# Generated by Django 5.2.1 on 2025-06-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imoveis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('tamanho', models.CharField(blank=True, max_length=20, null=True)),
                ('quartos', models.CharField(blank=True, max_length=20, null=True)),
                ('vagas', models.CharField(blank=True, max_length=20, null=True)),
                ('suites', models.CharField(blank=True, max_length=20, null=True)),
                ('plantas', models.CharField(blank=True, max_length=20, null=True)),
                ('data_extracao', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'imoveis',
                'managed': True,
            },
        ),
    ]
